[package]
name = "ph"
version = "0.1.0"
edition = "2018"

[lib]
name = "ph_rs"
crate-type = ["cdylib"]
path = "./topocluster/rust/lib.rs"

[dependencies]
numpy = "*"
ndarray = "*"

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]
